### ISSUE TITLE
Uncaught RangeError when triggering event with big array in parameter

### ISSUE THREAD

**Issue by Semigradsky** [jquery/jquery#2494]
```js
var arr = [];
for(var i = 0; i <= 85000; i++) {
    arr.push(i);
}

var el = jQuery('body');
el.on('test-event', function(){});
el.trigger('test-event', arr);
```
> Uncaught RangeError: Maximum call stack size exceeded
    at HTMLDivElement.jQuery.event.dispatch (https://code.jquery.com/jquery-1.11.3.js:4670:9)
    at HTMLDivElement.elemData.handle (https://code.jquery.com/jquery-1.11.3.js:4338:46)
    at Object.jQuery.event.trigger (https://code.jquery.com/jquery-1.11.3.js:4579:12)
    at HTMLDivElement.<anonymous> (https://code.jquery.com/jquery-1.11.3.js:5289:17)
    at Function.jQuery.extend.each (https://code.jquery.com/jquery-1.11.3.js:384:23)
    at jQuery.fn.jQuery.each (https://code.jquery.com/jquery-1.11.3.js:136:17)
    at jQuery.fn.extend.trigger (https://code.jquery.com/jquery-1.11.3.js:5288:15)
    at <anonymous>:10:3
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)

---
Looks like the problem in these lines (https://github.com/jquery/jquery/blob/master/src/event.js#L323-L325). `data` not wrapped to array if it is array:
```js
		data = data == null ?
			[ event ] :
			jQuery.makeArray( data, [ event ] );
```

**Comment by gibson042** [comment]
[As documented](http://api.jquery.com/trigger/), every element in an Array (actually, any Array-like) passed to `.trigger` becomes a handler argument. Since Javascript engines fare poorly with excessive argument counts, I recommend wrapping large arrays to avoid such expansion: http://jsfiddle.net/Lp3ox7rh/
