### ISSUE TITLE
building 1.8.3 fails

### ISSUE THREAD

**Issue by donnut** [jquery/jquery#2646]
I'm trying to build version 1.8.3,. I understand this is an old version, but we are trying that make a custom build.
The build process fails with the following errors:
```
Loading "test.js" tasks and helpers...ERROR
>> Error: No such module: evals
Loading "compare-size.js" tasks and helpers...ERROR
>> TypeError: Cannot read property '_' of undefined
```
I'm using node 0.12.7
The steps I performed were:
```
git clone ...
git checkout 1.8.3
npm install
grunt
```
I'm using grunt@0.3.17 (as defined in package.json)

Any help is appreciated!

BTW running grunt --verbose yields:
```
Initializing
Command-line options: --verbose

Registering built-in tasks.
Loading "concat.js" tasks and helpers...OK
Tasks: concat
Helpers: concat
Loading "init.js" tasks and helpers...OK
Tasks: init
Helpers: prompt, prompt_for_obj, prompt_for, git_origin, github_web_url
Loading "lint.js" tasks and helpers...OK
Tasks: lint
Helpers: lint
Loading "min.js" tasks and helpers...OK
Tasks: min
Helpers: uglify, gzip, min_max_info
Loading "misc.js" tasks and helpers...OK
Helpers: config, json, strip_banner, file_strip_banner, file_template, banner
Loading "qunit.js" tasks and helpers...OK
Tasks: qunit
Helpers: phantomjs
Loading "server.js" tasks and helpers...OK
Tasks: server
Loading "test.js" tasks and helpers...ERROR
>> Error: No such module: evals
>>     at Error (native)
>>     at Object.<anonymous> (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/nodeunit/lib/utils.js:14:22)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/nodeunit/lib/nodeunit.js:13:13)
>>     at Module._compile (module.js:460:26)
Loading "watch.js" tasks and helpers...OK
Tasks: watch

Reading "grunt.js" config file...OK
Reading dist/.destination.json...ERROR
Reading .jshintrc...OK
Parsing .jshintrc...OK
Reading .jshintrc...OK
Reading src/.jshintrc...OK
Parsing src/.jshintrc...OK
Reading src/.jshintrc...OK
Reading test/.jshintrc...OK
Parsing test/.jshintrc...OK
Reading test/.jshintrc...OK
Initializing config...OK
Reading package.json...OK
Parsing package.json...OK

Registering "grunt-compare-size" local Npm module tasks.
Reading /home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt-compare-size/package.json...OK
Parsing /home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt-compare-size/package.json...OK
Loading "compare-size.js" tasks and helpers...ERROR
>> TypeError: Cannot read property '_' of undefined
>>     at Object.module.exports (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt-compare-size/tasks/compare-size.js:22:12)
>>     at loadTask (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:163:10)
>>     at /home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:199:7
>>     at Array.forEach (native)
>>     at loadTasks (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:197:8)
>>     at Task.task.loadNpmTasks (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:330:5)
>>     at Object.module.exports (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/grunt.js:134:8)
>>     at loadTask (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:163:10)
>>     at Task.task.init (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt/task.js:386:5)
>>     at Object.grunt.tasks (/home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt/lib/grunt.js:113:8)

Registering "grunt-git-authors" local Npm module tasks.
Reading /home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt-git-authors/package.json...OK
Parsing /home/donnut/dev/js/jqueryconfig/assets/jquery-1.8.3/node_modules/grunt-git-authors/package.json...OK
Loading "git-authors.js" tasks and helpers...OK
Tasks: authors, update-authors
Loading "grunt.js" tasks and helpers...OK
Tasks: default, dev, testswarm, selector, custom, build, submodules, dist

No tasks specified, running default tasks.
Running tasks: default

Running "default" task
<WARN> Task "compare_size" not found. Use --force to continue. </WARN>

Aborted due to warnings.

```

**Comment by dmethvin** [comment]
I don't know a specific cause/solution but here are a few things to try.

Try the `1.8.3+1` tag, there were some changes made to fix build issues. https://github.com/jquery/jquery/compare/1.8.3...1.8.3+1

Also you might need an older node/npm, we were running something around 0.8 at the time.

The grunt-compare-size task can be skipped, it's not essential.

**Comment by timmywil** [comment]
We're happy to assist with this issue, but since it doesn't pertain to current jQuery, I'm closing this ticket in the interest of triage. Please try Dave's suggestion and let us know if that worked for you.

**Comment by donnut** [comment]
@dmethvin, thanks for your suggestion.
I can confirm that version `1.8.3` (and `1.8.3+1`) builds using node `v0.10.40`

`grunt-compare-size` keeps complaining, but that's not important indeed.
