### ISSUE TITLE
jQuery 2.2 and YUI Compressor 2.4.8 results in syntax errors

### ISSUE THREAD

**Issue by stepand76** [jquery/jquery#2862]
YUI Compressor 2.4.8 reports syntax errors while processing official uncompressed jquery-2.2.0.js file.  With jquery-2.1.4.js it works fine. Any ideas where is the issue?

https://github.com/yui/yuicompressor/issues/234

**Comment by dmethvin** [comment]
Yes, most likely it is because YUI Compressor still thinks `throws` is a reserved word even though it is not in any implementation. We took our our workaround for that in this release, but it should have been fixed years ago since we reported it back then. None of jQuery's supported browsers have required quoting this for several years.

https://bugs.jquery.com/ticket/12158 
https://github.com/yui/yuicompressor/issues/171 
https://github.com/yui/yuicompressor/issues/114

**Comment by fiatux** [comment]
I am getting syntax errors on 2.2.0 but 2.1.4 is even worse:

```
[Assetic\Exception\FilterException]                                                                                                                                
  An error occurred while running:                                                                                                                                   
  '/usr/bin/java' '-jar' '/var/www/domain.com/site/app/../vendor/packagist/yuicompressor-bin/bin/yuicompressor.jar' '--charset' 'UTF-8' '-o' '' '--type' 'js' ''   
  Error Output:                                                                                                                                                      
  java.io.FileNotFoundException:  (No such file or directory)                                                                                                        
  	at java.io.FileInputStream.open(Native Method)                                                                                                                    
  	at java.io.FileInputStream.<init>(FileInputStream.java:146)                                                                                                       
  	at java.io.FileInputStream.<init>(FileInputStream.java:101)                                                                                                       
  	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:133)                                                                                   
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                    
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)                                                                                  
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                          
  	at java.lang.reflect.Method.invoke(Method.java:606)                                                                                                               
  	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)  
```

**Comment by timmywil** [comment]
@fiatux That's not a syntax error. That a File Not Found error. It seems like it's not even running on jQuery.

**Comment by fiatux** [comment]
@timmywil as i told i was getting synxtax errors on 2.2.0, since i switched to 2.1.4 i am getting this filenotfound errors.
