### ISSUE TITLE
Tools UI issue while building 3.2 

### ISSUE THREAD

**Issue by sriranjinidey** [jquery/jquery#2997]
Tools UI is throwing this error . Please help

caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'grunt --bsp-maven-build-finalName=cms-tool-ui-3.2-SNAPSHOT --no-color' failed. (error code 3)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
	at com.github.eirslett.maven.plugins.frontend.mojo.GruntMojo.execute(GruntMojo.java:64)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:67)

**Comment by dmethvin** [comment]
This does not sound like a jQuery Core issue, I think you meant to file this somewhere else.

**Comment by sriranjinidey** [comment]
sorry. Yes. I have posted it to where it belongs.
