### ISSUE TITLE
IE11 - Script 5007: Unable to get property 'style' of undefined or null reference

### ISSUE THREAD

**Issue by AvexMedia** [jquery/jquery#3273]
jQuery 3.1.0 stops execution on Internet Explorer 11 and 10 (VirtualBox, Windows 7) on first load, when website has not been cached yet with the following error message:

**Script 5007: Unable to get property 'style' of undefined or null reference**

This refers to **function computeStyleTests()**, in particular to `div.style.marginRight="50%";`

This basically stops any script from being executed on the page. The error disappears if the page is reloaded. In IE10 and lower it silently fails without any error message.

This problem does not appear on any other modern browser or platform.

**Comment by dmethvin** [comment]
We need more information from you to figure it out. By the time it reaches the line you mentioned, it has already used `div.style` just above so I'm not sure how that error could occur. Is there anything special about this page, for example is it an XML/XSL page? Can you provide a test case?

**Comment by AvexMedia** [comment]
This is a normal HTML5 page. The problem is that the code does not break in any other browser and the error only appears inside the mentioned jQuery function without any reference to the div that might fail. 

In what cases is computeStyleTests() normally applied? Maybe that could help to figure out to which div it refers...

**Comment by dmethvin** [comment]
> In what cases is computeStyleTests() normally applied? Maybe that could help to figure out to which JS or div it refers...

It's the CSS feature detection code, which is [here for 3.1.0](https://github.com/jquery/jquery/blob/d0d2d9b9b004cf0c6763c871646e01ca67579253/src/css/support.js).  Set a breakpoint before the line that changes and see what `div` is.

**Comment by AvexMedia** [comment]
Setting a breakpoint at `boxSizingReliableVal = divStyle.width === "4px";` (just before the line that fails) and clicking 'continue' will execute the script without further error or reference to a specific div.

**Comment by dmethvin** [comment]
Unless you have a test case we can't really do much more.

**Comment by AvexMedia** [comment]
Tried to manually uncomment my JS block by block to identify the underlying problem without much success so far. I assume [qUnit](https://qunitjs.com/) would be the way to go here for a test case?

**Comment by dmethvin** [comment]
Ideally the test case should just be a HTML file that includes only jQuery. If you can't get it to work on jsbin or jsfiddle, just create a standalone one and we can work from there.

**Comment by gjboudreaux** [comment]
A co-worker of mine is experiencing the same issue in IE11.  I cannot reproduce this in IE11 on my computer.

I loaded the uncompressed version of jquery 3.1.0 and he receives the following console error:

SCRIPT5007: Unable to get property 'style' of undefined or null reference 
File: jquery-3.1.0.js, Line: 3793, Column: 3

If I revert to jquery-2.2.3.js he doesn't have any issues.

As a side note, we are also using jquery-UI 1.12.0.

I am not sure I can strip down my project to a workable test case.

**Comment by dmethvin** [comment]
You've tested with jQuery Migrate, right?

**Comment by gjboudreaux** [comment]
I added Migrate 3.0.0 and he gets the following console output.  I get the same console output, however where he gets the "SCRIPT5007: Unable to get property 'style' of undefined or null reference" error, I do not and the page executes normally for me.  When he refreshes the page, it loads normally without the error.  We both have the same version of IE11.  I am not sure if every setting is the same.

HTML1300: Navigation occurred.
File: screenManager.html
JQMIGRATE: Migrate is installed with logging active, version 3.0.0
JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos
console.trace()
   at migrateWarn (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:64:5)
   at unique.get (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:75:4)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:17117)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:73)
   at Global code (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:2)
JQMIGRATE: jQuery.expr.filters is now jQuery.expr.pseudos
console.trace()
   at migrateWarn (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:64:5)
   at unique.get (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:75:4)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:13:11019)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:13:10077)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:73)
   at Global code (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:2)
JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort
console.trace()
   at migrateWarn (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:64:5)
   at unique.get (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY/jquery-migrate-3.0.0.js:75:4)
   at i (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:8547)
   at t.Widget.prototype._classes (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:8730)
   at t.Widget.prototype._toggleClass (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:9174)
   at t.Widget.prototype._addClass (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:6:8988)
   at _createWrapper (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY-UI/jquery-ui-1.12.0.min.js:11:10885)
   at Anonymous function (http://lmstest.ebs.fedex.com/_MOBILE_TEST_FUTURE/screenManager/_JQUERY
SCRIPT5007: Unable to get property 'style' of undefined or null reference
File: jquery-3.1.0.js, Line: 3793, Column: 3

**Comment by gjboudreaux** [comment]
Another test.  Downgraded jQuery UI to 1.11.4 and tested with jQuery 3.1.0.  He does not get the error.  it seems that something in jQuery UI 1.12.0 is causing the issue.

**Comment by dmethvin** [comment]
In the original ticket template when you created the ticket, there were instructions and a request for a test case. Did that appear for you? It would be helpful to have some sort of test case. It sounds like there may be some sort of regression condition in 3.0 related to jQuery UI that we haven't considered but without a test case it would be very difficult to diagnose.

**Comment by gjboudreaux** [comment]
I didn't open this ticket.  I am having the same issue and started searching for a possible solution and came across this ticket.  I am not sure if AvexMedia, the person who opened this ticket, is also using jQuery UI.  I'll try to strip my framework down into a working test case.

**Comment by AvexMedia** [comment]
As this problem appeared in a website project that is almost production-ready, I am currently having difficulties to strip this down to a testable case. But I will see what I can do.

Nevertheless, I did not use jQuery UI.

Adding jQuery Migrate 3.0.0 gives me the following warning message every time directly before the mentioned 5007 on IE11:

`JQMigrate : jQuery.expr[":"] is now jQuery.expr.pseudos`

**Comment by timmywil** [comment]
As this issue has gotten stale without at test case, closing.

**Comment by arisliang** [comment]
suspect this might have to do with compatibility view on IE11. I was having the same issue with compatibility view checked. Once uncheck, the issue was gone.

**Comment by rthadhani** [comment]
I got similar error when I am trying to get the value passed in the QueryString of an URL.
 var parameterPage = url.searchParams.get("page");

Please help
