### ISSUE TITLE
.find() returns plain HTML object instead of jQuery object

### ISSUE THREAD

**Issue by Zebradil** [jquery/jquery#3575]
### Description ###

```javascript
var jsdom = require("jsdom");
var jquery = require("jquery");

jsdom.env("<div><span></span></div>", (err, window) => {
    let $ = jquery(window);
    let $div = $.find("div");
    console.log($div);
    console.log($div.find("span"));
});
```
Output:
```
[ HTMLDivElement {} ]
/Users/german/development/my.projects/JBootoc/jquery.test.js:8
    console.log($div.find("span"));
                     ^

TypeError: span is not a function
    at Array.find (native)
    at Object.jsdom.env [as done] (/Users/german/development/my.projects/JBootoc/jquery.test.js:8:22)
    at process.nextTick (/Users/german/development/my.projects/JBootoc/node_modules/jsdom/lib/jsdom.js:325:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Package versions:

```
jquery@3.2.0
jsdom@9.12.0
```

Node version: `v7.7.3`

**Comment by timmywil** [comment]
`jQuery.find` is different than `jQuery.fn.find`. One is a static method and the other is on the jQuery prototype. For more information, please consult the jQuery docs or ask for help on stackoverflow, in the [jQuery forums](forums.jquery.com), or in the [jQuery Gitter channel](https://gitter.im/jquery/jquery).

**Comment by Zebradil** [comment]
Yes, I mixed it up.
There should be one more step before `find`:
```javascript
let $div = $(window.document).find("div");
```
That works.

Thanks!)
