### ISSUE TITLE
Uncaught Exception in HTMLUnit

### ISSUE THREAD

**Issue by laDanz** [jquery/jquery#3829]
Somehow this line causes HTMLUnit (version 2.27) to crash hard. JQuery cannot be fully loaded, so further processing on my website is not possible.

https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/core/support.js#L15

Could you please wrap it by try/catch or assert?

> com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot set property "innerHTML" of undefined to "<form></form><form></form>" (http://localhost:8480/static/javascript/jquery-3.2.1.min-ver-9C3A8D5BF79A2B2C25B4D9F99FBF6DB2.js#9761)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:894) ~[htmlunit-2.27.jar:2.27]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:637) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:518) ~[htmlunit-core-js-2.27.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:774) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:750) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:102) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:991) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:366) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:247) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:268) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:800) ~[htmlunit-2.27.jar:2.27]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:756) ~[htmlunit-2.27.jar:2.27]
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1236) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1136) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:226) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:345) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3178) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2141) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:945) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:521) ~[neko-htmlunit-2.27.jar:?]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:472) ~[neko-htmlunit-2.27.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:999) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:250) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:192) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:272) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:160) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:522) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:396) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:313) ~[htmlunit-2.27.jar:2.27]
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:668) ~[htmlunit-driver-2.27.jar:?]
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$8(HtmlUnitDriver.java:655) ~[htmlunit-driver-2.27.jar:?]
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$0(HtmlUnitDriver.java:412) ~[htmlunit-driver-2.27.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot set property "innerHTML" of undefined to "<form></form><form></form>" (http://localhost:8480/static/javascript/jquery-3.2.1.min-ver-9C3A8D5BF79A2B2C25B4D9F99FBF6DB2.js#9761)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3915) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3899) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3924) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:3946) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.undefWriteError(ScriptRuntime.java:3963) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1641) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1265) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:800) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:416) ~[htmlunit-core-js-2.27.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322) ~[htmlunit-2.27.jar:2.27]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3264) ~[htmlunit-core-js-2.27.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115) ~[htmlunit-core-js-2.27.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:765) ~[htmlunit-2.27.jar:2.27]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:879) ~[htmlunit-2.27.jar:2.27]
	... 34 more

**Comment by dmethvin** [comment]
> Somehow

That's the key thing, isn't it? There isn't enough information here to determine the problem, and having jQuery try to mask this doesn't even make sense until the "somehow" is resolved. Nobody else has reported this problem so you'll need to provide more information,

**Comment by laDanz** [comment]
Maybe the error is caused in the line above:
https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/core/support.js#L14
and more precisely the faulty implementation of this code at the HTMLUnit end?

**Comment by timmywil** [comment]
We need a test case in order to assess any possible issue, preferably from jsfiddle.net or jsbin.com.
