### ISSUE TITLE
Identifier 'r' has already been declared

### ISSUE THREAD

**Issue by Maxim-Mazurok** [jquery/jquery#5247]
### Description ###

Got an exception in the jQuery 3.6.0, using with AngularJS 1.8.2:

```
SyntaxError: Identifier 'r' has already been declared
  at b(/assets/vendor/jquery/3.6.0/jquery.min.js:2:866)
  at He(/assets/vendor/jquery/3.6.0/jquery.min.js:2:48373)
  at S.fn.init.append(/assets/vendor/jquery/3.6.0/jquery.min.js:2:49724)
  at S.fn.init.<anonymous>(/assets/vendor/jquery/3.6.0/jquery.min.js:2:50816)
  at $(/assets/vendor/jquery/3.6.0/jquery.min.js:2:32425)
  at S.fn.init.html(/assets/vendor/jquery/3.6.0/jquery.min.js:2:50494)
  at <object>.link(angular.js:29992:9)
  at linkFn(angular.js:1391:15)
  at invokeLinkFn(angular.js:11376:9)
  at nodeLinkFn(angular.js:10695:11)
  at compositeLinkFn(angular.js:9942:13)
  at apply(angular.js:9807:30)
  at transcludeFn(angular.js:10221:16)
  at boundTranscludeFn(angular.js:9985:16)
  at controllersBoundTransclude(angular.js:10745:20)
  at fn(angular.js:29939:27)
  at fn(angular.js:18075:37)
  at Scope.prototype.$digest(angular.js:19242:15)
  at Scope.prototype.$apply(angular.js:19630:13)
  at done(angular.js:13473:36)
  at completeRequest(angular.js:13730:7)
  at xhr.onload(angular.js:13635:9)
  at sentryWrapped(node_modules/@sentry/browser/dist/helpers.js:70:1)
```

On Chrome 112.0.0

Right after the template was loaded.

The issue seems to be inside of `DOMEval` function in jQuery. I set breakpoints trying to see when it's being hit, but I can't reproduce.

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

Also, if you could use non-minified versions of the libraries for the test case, it'd help as well.

**Comment by mgol** [comment]
I will add that there's a 99% chance this error means an error in a script that is being evaluated by jQuery here - so no error in jQuery code itself.

**Comment by Maxim-Mazurok** [comment]
Hi @mgol I couldn't reproduce the issue.
I've used https://sourcemaps.info/ to map from minified to original sources (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js + https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.map):
```
SyntaxError: Identifier 'r' has already been declared
  at b(jquery.js:133:11)
  at He(jquery.js:6114:7)
  at S.fn.init.append(jquery.js:6250:9)
  at S.fn.init.<anonymous>(jquery.js:6344:17)
  at $(jquery.js:4171:7)
  at S.fn.init.html(jquery.js:6311:9)
  at <object>.link(angular.js:29992:9)
  at linkFn(angular.js:1391:15)
  at invokeLinkFn(angular.js:11376:9)
  at nodeLinkFn(angular.js:10695:11)
  at compositeLinkFn(angular.js:9942:13)
  at apply(angular.js:9807:30)
  at transcludeFn(angular.js:10221:16)
  at boundTranscludeFn(angular.js:9985:16)
  at controllersBoundTransclude(angular.js:10745:20)
  at fn(angular.js:29939:27)
  at fn(angular.js:18075:37)
  at Scope.prototype.$digest(angular.js:19242:15)
  at Scope.prototype.$apply(angular.js:19630:13)
  at done(angular.js:13473:36)
  at completeRequest(angular.js:13730:7)
  at xhr.onload(angular.js:13635:9)
  at sentryWrapped(node_modules/@sentry/browser/dist/helpers.js:70:1)
```

this is where the error was thrown:
![image](https://github.com/jquery/jquery/assets/7756211/c193462c-3f29-41b8-8790-bf1f3609346b)

And here's the same place in minified code:
![image](https://github.com/jquery/jquery/assets/7756211/58fcdc13-f063-4dec-9aad-da9ad4b15b04)


It looks weird because it points to `doc.head`, not to the `var r` or anything like that.

So yeah, I think your explanation makes sense, the error was probably thrown from the script that jQuery attempted to evaluate when it was added to the document head.

That's a pretty good explanation IMO, so I'll close this for now, thank you!
