### ISSUE TITLE
Cannot read properties of null (reading 'compareDocumentPosition')

### ISSUE THREAD

**Issue by mrsai** [jquery/jquery#5401]
### Description ###

In most cases, this is correct, but I'm not sure what triggered the issue or where it originated. The browser gave me a prompt like this：
```
VM102146 vendor.js:147289 Uncaught TypeError: Cannot read properties of null (reading 'compareDocumentPosition')
    at sortOrder (VM102146 vendor.js:147289:20)
    at Array.sort (<anonymous>)
    at jQuery.uniqueSort (VM102146 vendor.js:147430:7)
    at jQuery.fn.init.add (VM102146 vendor.js:148967:11)
    at d.e (src_util_xtPlayer_XtPlayer_min_js.js:22:514765)
    at HTMLDocument.dispatch (VM102146 vendor.js:151068:27)
    at elemData.handle (VM102146 vendor.js:150872:28)
    at Object.trigger (VM102146 vendor.js:154552:12)
    at HTMLDocument.<anonymous> (VM102146 vendor.js:154630:17)
    at Function.each (VM102146 vendor.js:146306:19)
    at jQuery.fn.init.each (VM102146 vendor.js:146128:17)
    at jQuery.fn.init.trigger (VM102146 vendor.js:154629:15)
    at r._triggerEvents (src_util_xtPlayer_XtPlayer_min_js.js:22:274154)
    at r._fullScreenChange (src_util_xtPlayer_XtPlayer_min_js.js:22:273768)
    at HTMLDocument.proxy (VM102146 vendor.js:156538:13)
    at HTMLDocument.dispatch (VM102146 vendor.js:151068:27)
```

debug in src/selector/uniqueSort.js

```
function sortOrder( a, b ) {
   ...
   var compare = !a.compareDocumentPosition - !b.compareDocumentPosition;
   ...
}
```
I'm not sure why ’a‘ is null. 
Is it necessary to impose a constraint ?

**Comment by mgol** [comment]
Just seeing an error does not give us a lot to work with. We do need a runnable test case as the issue template asked.

**Comment by mrsai** [comment]
thank you for your contribution. I have carefully reviewed the relevant code and confirmed that it is not a bug but an issue caused by the developer's misuse of jQuery. In certain places, the developer attempted to set a DOM element of a jQuery object to null, which resulted in the problem.
···
// bad code
this.player.$video[0] = null;
···

**Comment by mrsai** [comment]
I apologize for the inconvenience and for taking up your time. This was indeed our mistake. Please  close it for. Thank you once again.
