### ISSUE TITLE
jQuery.get() 4.0 backward compatibility issue

### ISSUE THREAD

**Issue by hugodevreugd** [jquery/jquery#5426]
The jQuery api describes jQuery.get as: jQuery.get( url [, data ] [, success ] [, dataType ] )].

In jQuery 3.5.7 this code, with null for the data parameter, works:
```
var jqxhr = $.get( "example.php", null, function() {
  alert( "success" );
});
```

In jQuery 4.0 this code doesn't work anymore, you have to remove the null parameter:
```
var jqxhr = $.get( "example.php", function() {
  alert( "success" );
});
```

A small change, but this breaks backward compatibility.

**Comment by dmethvin** [comment]
The [docs](https://api.jquery.com/jQuery.get/#jQuery-get-url-data-success-dataType) don't say that you can use `null` for data, it's supposed to be an object or string. According to https://github.com/jquery/jquery/pull/5139#discussion_r996276727  and the docs, `null` is used to omit the callback. The second example omits data without needing to mention it at all. Worth a mention in the upgrade guide though I guess?

**Comment by timmywil** [comment]
Thanks for the issue and thanks for pointing that out, Dave. We'll mention it in the upgrade guide.

**Comment by rexfactor** [comment]
Has anyone here come across this error when using $.get() ? Also, I was using the hosted library served up by Google when I first got the message so I then loaded a local file of 3.6. 

jquery-3.6.0.min.js:2 Uncaught TypeError: t.call is not a function
    at Function.each (jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (jquery-3.6.0.min.js:2:1481)
    at Object.success ((index):21:15)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.min.js:2:82355)

**Comment by Chefaroon** [comment]
> The [docs](https://api.jquery.com/jQuery.get/#jQuery-get-url-data-success-dataType) don't say that you can use `null` for data, it's supposed to be an object or string.

Ehm, in JavaScript "null" IS an Object. I don't agree with it, but it is. Easiest check - development console:
```
> console.log(typeof null);
object
```

**Comment by mgol** [comment]
`null` is not an object. The fact `typeof null === "object"` is a language bug but it doesn't change the fact that `null` is a primitive, not an object.

See:
* https://tc39.es/ecma262/#sec-primitive-value
* https://tc39.es/ecma262/#sec-terms-and-definitions-object
* https://tc39.es/ecma262/#sec-object-type

Also, note the error message here:
```js
Object.getPrototypeOf(null);
// Uncaught TypeError: Cannot convert undefined or null to object
```

**Comment by rexfactor** [comment]
Null is an object when called in a function.

**Comment by rexfactor** [comment]
Think of it this way, a function that is designed to return an object based
on a set criteria must return an object because that is what it is designed
to detect. If it returns null, meaning the object is absent, the object
that the function returns is an empty object indicating that what it was
looking for was not there.

In essence, null isn't an object but rather the function is an object with
the value of null.

**Comment by cyfung1031** [comment]
I think 
```
$.get( url, null, fn);
```

is a very common syntax.
this is intentional that passing a null object in 2nd argument to represent "NO DATA" in order to add success and error callbacks.

This is a serious issue that backward compatibility issue cannot be met as it is not due to the browser standard changed

**Comment by mgol** [comment]
Issues have been documented at https://github.com/jquery/api.jquery.com/pull/1208 and we added tests in a few Core PRs. I think that's all we need here.
